// <auto-generated />
using System;
using BrowserSync.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrowserSync.Core.Data.Migrations
{
    [DbContext(typeof(BrowserSyncDbContext))]
    [Migration("20260804231058_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("BrowserSync.Core.Data.Entities.CanonicalBookmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LastModifiedByClientId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleRoot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("CanonicalBookmarks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Kind = 1,
                            LastModifiedUtc = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleRoot = 1,
                            SortIndex = 0,
                            Title = "Bookmarks Bar"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Kind = 1,
                            LastModifiedUtc = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleRoot = 2,
                            SortIndex = 1,
                            Title = "Other Bookmarks"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Kind = 1,
                            LastModifiedUtc = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleRoot = 3,
                            SortIndex = 2,
                            Title = "Mobile Bookmarks"
                        });
                });

            modelBuilder.Entity("BrowserSync.Core.Data.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BrowserKind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastReconciledUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("BrowserSync.Core.Data.Entities.ClientBookmarkMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CanonicalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NativeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "CanonicalId")
                        .IsUnique();

                    b.HasIndex("ClientId", "NativeId")
                        .IsUnique();

                    b.ToTable("ClientBookmarkMappings");
                });

            modelBuilder.Entity("BrowserSync.Core.Data.Entities.Tombstone", b =>
                {
                    b.Property<Guid>("CanonicalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeletedByClientId")
                        .HasColumnType("TEXT");

                    b.HasKey("CanonicalId");

                    b.ToTable("Tombstones");
                });

            modelBuilder.Entity("BrowserSync.Core.Data.Entities.CanonicalBookmark", b =>
                {
                    b.HasOne("BrowserSync.Core.Data.Entities.CanonicalBookmark", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);
                });
#pragma warning restore 612, 618
        }
    }
}
